language: python
python:
    - "3.6"
servies:
  - docker

  before_script: pip install docker-compose

  script:
    - docker-compose run app sh -c "python manage.py test && flak8"

    flake8>=3.6.0<3.7.0
